<?xml version = "1.0" encoding = "UTF-8" ?>
<p:DCTRequest xmlns:p="http://www.dhl.com" xmlns:p1="http://www.dhl.com/datatypes" xmlns:p2="http://www.dhl.com/DCTRequestdatatypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dhl.com DCT-req.xsd ">
  <GetQuote>
    <Request>
      <ServiceHeader>
        <MessageTime>2012-07-25T03:17:23+00:00</MessageTime>
        <MessageReference>4679297471568754589566428971129</MessageReference>
        <SiteID>APMediaM9</SiteID>
        <Password>apwoEM27X</Password>
      </ServiceHeader>
    </Request>
    <From>
      <CountryCode>ID</CountryCode>
      <Postalcode>10410</Postalcode>
    </From>
    <BkgDetails>
      <PaymentCountryCode>ID</PaymentCountryCode>
      <Date>2012-07-25</Date>
      <ReadyTime>PT10H21M</ReadyTime>
      <ReadyTimeGMTOffset>+01:00</ReadyTimeGMTOffset>
      <DimensionUnit>CM</DimensionUnit>
      <WeightUnit>KG</WeightUnit>
      <Pieces>
        <Piece>
				<PieceID>1</PieceID>
				<Height>1</Height>
				<Depth>1</Depth>
				<Width>1</Width>
				<Weight>1</Weight>
        </Piece>
      </Pieces> 
      <IsDutiable>Y</IsDutiable>
      <NetworkTypeCode>AL</NetworkTypeCode>	
      <InsuredValue>0</InsuredValue>
      <InsuredCurrency>USD</InsuredCurrency>
    </BkgDetails>
    <To>
      <CountryCode>SG</CountryCode>
      <Postalcode>912345</Postalcode>
			<City></City>
    </To>
		<Dutiable>
      <DeclaredCurrency>USD</DeclaredCurrency>
      <DeclaredValue>10.0</DeclaredValue>
    </Dutiable>
  </GetQuote>
</p:DCTRequest>